### ISSUE TITLE
error about convert TOUGH2 output to TOUGH3 OUTPUT_ELEME.csv file

### ISSUE THREAD

**Issue by BourbonTiger** [keurfonluu/toughio#150]
I have used the following command to convert the OUTPUT file into a mesh file (.csv):
toughio-extract OUTPUT MESH
However, I keep getting this error: 

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\DELL\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\Scripts\toughio-extract.exe\__main__.py", line 7, in <module>
  File "C:\Users\DELL\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\toughio\_cli\_extract.py", line 43, in extract
    output = read_output(args.infile, connection=args.connection)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\toughio\_io\output\_helpers.py", line 78, in read
    file_type, file_format = get_output_type(filename)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\toughio\_io\output\_helpers.py", line 145, in get_output_type
    raise ValueError()
ValueError

Did I miss parameter？
I am enclosing the input, output and MESH files here.

[flow.txt](https://github.com/keurfonluu/toughio/files/12505072/flow.txt)

[MESH.txt](https://github.com/keurfonluu/toughio/files/12505067/MESH.txt)

[OUTPUT.txt](https://github.com/keurfonluu/toughio/files/12505068/OUTPUT.txt)

**Comment by BourbonTiger** [comment]
I found maybe it`s because when the first line in the file must be  @ symbols  get_Output_type function can work well.

**Comment by keurfonluu** [comment]
Hi @BourbonTiger,

It seems that you are using TOUGHREACT, which has not been tested with toughio, although flow part should work.
Indeed, if you remove all the lines before the TOUGH SIMULATION RUN in @, the function should work because the automatic output format detection is relying on this to know which parser to use.

In a script, you can use (although the X, Y, Z coordinates will be missing):

```python
outputs = toughio.read_output("OUTPUT.txt", file_format="tough")
toughio.write_output("OUTPUT_ELEME.csv", outputs)
```

**Comment by BourbonTiger** [comment]
thanks !!

**Comment by BourbonTiger** [comment]
Thank you!!
