### ISSUE TITLE
Questions about the use of toughio-extract out MESH

### ISSUE THREAD

**Issue by mingnan-sun** [keurfonluu/toughio#172]
I am quite new to TOUGH2 and have been attempting to run Problem No. 7 (r2dl) - NAPL Spill in the Unsaturated Zone. However, I encountered an error while using the **toughio-extract out MESH** command to convert the file format. The error message is as follows:

D:\Sci\tough_example\part3>toughio-extract.exe out MESH
Traceback (most recent call last):
  File "D:\App\anaconda3\envs\statis\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\App\anaconda3\envs\statis\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Nancy\AppData\Roaming\Python\Python39\Scripts\toughio-extract.exe\__main__.py", line 7, in <module>
  File "C:\Users\Nancy\AppData\Roaming\Python\Python39\site-packages\toughio\_cli\_extract.py", line 48, in extract
    [parameters["elements"][label]["center"] for label in output[-1].labels]
AttributeError: 'dict' object has no attribute 'labels'

These are my input files: 
[MESH.txt](https://github.com/user-attachments/files/16895959/MESH.txt)
[out.txt](https://github.com/user-attachments/files/16895960/out.txt)
I would greatly appreciate any assistance in resolving this issue.

**Comment by geowomen** [comment]
Hi i download your files and it works for me : 
![image](https://github.com/user-attachments/assets/73098046-2697-4ade-bc3c-747f790b0aa1)
![image](https://github.com/user-attachments/assets/28d5f4d0-10fb-4cde-b011-15b03efc9120)
